#!/bin/sh
sudo service uwsgi restart
sudo service nginx restart
ps auxww | grep 'celery' | awk '{print $2}' | xargs kill -9
ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9
ps auxww | grep 'celerybeat' | awk '{print $2}' | xargs kill -9
rm celeryd.pid
export C_FORCE_ROOT="true"
python manage.py celeryd_detach