# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import files_widget.fields
import tagging_autocomplete_tagit.models
import re
import ckeditor.fields
import multiselectfield.db.fields
from django.conf import settings
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '__first__'),
        ('taxonomy', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ordering', models.PositiveIntegerField(null=True, blank=True)),
                ('title', models.CharField(max_length=255)),
                ('contact_information', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('role', models.CharField(blank=True, max_length=128, null=True, choices=[(b'administration', b'Administration'), (b'analyst-scientist', b'Analyst/Scientist'), (b'designer', b'Designer'), (b'finance-accounting', b'Finance/Accounting'), (b'hardware-engineer', b'Hardware Engineer'), (b'hr', b'HR'), (b'legal', b'Legal'), (b'management', b'Management'), (b'marketing-and-pr', b'Marketing and PR'), (b'operations', b'Operations'), (b'others', b'Others'), (b'product-manager', b'Product Manager'), (b'sales', b'Sales'), (b'software-engineer', b'Software Engineer')])),
                ('position', models.CharField(default=b'full-time', max_length=128, null=True, blank=True, choices=[(b'full-time', b'Full Time'), (b'contract', b'Contract'), (b'internship', b'Internship'), (b'cofounder', b'Cofounder')])),
                ('salary_min', models.PositiveIntegerField(null=True, blank=True)),
                ('salary_max', models.PositiveIntegerField(null=True, blank=True)),
                ('equity_min', models.DecimalField(null=True, max_digits=19, decimal_places=2, blank=True)),
                ('equity_max', models.DecimalField(null=True, max_digits=19, decimal_places=2, blank=True)),
                ('remote', models.NullBooleanField(default=False)),
                ('years_of_experience', models.PositiveIntegerField(null=True, blank=True)),
                ('location', models.CharField(max_length=255, null=True, blank=True)),
                ('skills', tagging_autocomplete_tagit.models.TagAutocompleteTagItField(max_length=255, null=True, blank=True)),
                ('status', models.IntegerField(default=1, choices=[(1, b'Active'), (-1, b'Close')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(related_name='job_country', blank=True, to='taxonomy.Country', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('party_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='party.Party')),
                ('permalink', models.CharField(help_text='Required unique 30 characters or fewer. Letters, numbers and ./@/+/-/_ characters', unique=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.+-]+$'), 'Enter a valid permalink.', b'invalid')])),
                ('report_start_date', models.DateField(help_text=b'Start date of the reporting period for this IRIS report.', null=True, verbose_name=b'Report Start Date', blank=True)),
                ('report_end_date', models.DateField(help_text=b'End date of the reporting period for this IRIS report.', null=True, verbose_name=b'Report End Date', blank=True)),
                ('year_founded', models.PositiveSmallIntegerField(help_text=b'Year the organization was founded.', null=True, verbose_name=b'Year Founded', blank=True)),
                ('name_of_representative', models.CharField(max_length=255, null=True, verbose_name=b'Name of representative', blank=True)),
                ('gender_of_representative', models.CharField(blank=True, max_length=1, null=True, verbose_name=b'Gender of representative', choices=[(b'M', b'Male'), (b'F', b'Female')])),
                ('brief_bio_of_representative', ckeditor.fields.RichTextField(null=True, verbose_name=b'Brief bio of representative', blank=True)),
                ('legal_structure', models.CharField(choices=[(b'1', b'Corporation'), (b'2', b'Limited Liability Company'), (b'3', b'Non-Profit/Foundation/Association'), (b'4', b'Partnership'), (b'5', b'Sole-proprietorship'), (b'6', b'Corporatives'), (b'Other', b'Other')], max_length=255, blank=True, help_text=b'Current legal structure of the organization.', null=True, verbose_name=b'Legal Structure')),
                ('location_of_organizations_headquarters', models.CharField(max_length=255, null=True, verbose_name=b"Location of Organization's Headquarters", blank=True)),
                ('store_phone_number_of_organizations_headquarters', models.TextField(null=True, blank=True)),
                ('email_of_contact_person', models.EmailField(max_length=255, null=True, verbose_name='Email of Contact Person', blank=True)),
                ('store_location_of_organizations_operating_facilities', models.TextField(null=True, verbose_name=b"Location of Organization's Operating Facilities", blank=True)),
                ('name_of_referring_organization', models.CharField(max_length=255, null=True, verbose_name=b'Name of referring organization', blank=True)),
                ('contact_information_of_referring_organization', models.CharField(max_length=255, null=True, verbose_name=b'Contact information of referring organization', blank=True)),
                ('target_beneficiary', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=255, null=True, verbose_name=b'Target Beneficiary', choices=[(b'1', b'Women'), (b'2', b'Diabilities'), (b'3', b'Children'), (b'4', b'Ethnic Minority'), (b'5', b'Elderly'), (b'6', b'NEET'), (b'7', b'Migrant Workers'), (b'8', b'Youth'), (b'9', b'LGBT'), (b'Other', b'Others')])),
                ('mission_statement', ckeditor.fields.RichTextField(help_text=b'Mission statement of the organization.', null=True, verbose_name=b'Mission Statement', blank=True)),
                ('productservice_description', ckeditor.fields.RichTextField(help_text=b'Description of the product or service.', null=True, verbose_name=b'Product/Service Description', blank=True)),
                ('definition_of_unit_of_measure_1', models.CharField(max_length=512, null=True, verbose_name=b'Definition of unit of measure 1', blank=True)),
                ('unit_of_impact_measurement_1', models.CharField(max_length=512, null=True, verbose_name=b'Unit of Impact Measurement 1', blank=True)),
                ('definition_of_unit_of_measure_2', models.CharField(max_length=512, null=True, verbose_name=b'Definition of unit of measure 2', blank=True)),
                ('unit_of_impact_measurement_2', models.CharField(max_length=512, null=True, verbose_name=b'Unit of Impact Measurement 2', blank=True)),
                ('definition_of_unit_of_measure_3', models.CharField(max_length=512, null=True, verbose_name=b'Definition of unit of measure 3', blank=True)),
                ('unit_of_impact_measurement_3', models.CharField(max_length=512, null=True, verbose_name=b'Unit of Impact Measurement 3', blank=True)),
                ('store_measurement_year_values', models.TextField(null=True, verbose_name=b'Measurement Year and Values', blank=True)),
                ('client_type', multiselectfield.db.fields.MultiSelectField(choices=[(b'1', b'Individuals/Households'), (b'2', b'Microenterprises'), (b'3', b'Small-to-Medium Enterprises'), (b'4', b'Large Enterprises'), (b'5', b'Non-profit / Non-Governmental Organization / Foundations'), (b'6', b'Government'), (b'7', b'International Organizations'), (b'Other', b'Others')], max_length=255, blank=True, help_text=b"Types of entities that are buyers or recipients of the organization's products and/or services", null=True, verbose_name=b'Client Type')),
                ('client_information', ckeditor.fields.RichTextField(help_text=b'Name of major clients, if they are business or government', null=True, verbose_name=b'Client Information', blank=True)),
                ('store_top_3_major_investors_year_and_amount', models.TextField(null=True, verbose_name=b'Top 3 major investors, year and amount', blank=True)),
                ('store_top_3_major_donors_year_and_amount', models.TextField(null=True, verbose_name=b'Top 3 major donors, year and amount', blank=True)),
                ('annual_revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Annual revenue', choices=[(b'1', b'Under $50K'), (b'2', b'$50K-$100K'), (b'3', b'$100K-$250K'), (b'4', b'$250K-$500K'), (b'5', b'$500K-$1MM'), (b'6', b'$1MM-$2MM'), (b'7', b'$1MM-$5MM'), (b'8', b'Over $5MM')])),
                ('revenue_model', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Revenue Model', choices=[(b'1', b'Social Business (Business revenue more than 75% of total revenue)'), (b'2', b'Hybird (Business revenue range 25% to 75% of total revenue)'), (b'3', b'Charity (Business revenue less than 25%)')])),
                ('earned_revenue', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Revenue resulting from all business activities during the reporting period. Earned revenue is total revenues less "Contributed Revenue" (Grants and Donations).', null=True, verbose_name=b'Earned Revenue')),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Direct costs attributable to the production of the goods sold by the organization during the reporting period.  The cost should include all costs of purchase, costs of conversion, and other direct costs incurred in producing and selling the organization's", null=True, verbose_name=b'Cost of Goods Sold')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"The organization's residual profit after selling a product or service and deducting the costs directly associated with its production. Gross Profit is 'Earned Revenue' less 'Cost of Goods Sold'.", null=True, verbose_name=b'Gross Profit')),
                ('personnel_expense', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Expenses related to personnel, including wages, benefits, trainings, and payroll taxes incurred by the organization during the reporting period.', null=True, verbose_name=b'Personnel Expense')),
                ('selling_general_and_administration_expense', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Sum of all direct and indirect selling expenses and all general and administrative expenses incurred by the organization during the reporting period.', null=True, verbose_name=b'Selling, General, and Administration Expense')),
                ('operating_expense', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Expenditures incurred by the organization as a result of performing its normal business operations. NOTE: For financial services companies this does not include Financial Expenses or provisions for loan losses (impairment losses).', null=True, verbose_name=b'Operating Expense')),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Organization's earnings, excluding contributed revenues, before interest, taxes, depreciation and amortization during the reporting period.", null=True, verbose_name=b'EBITDA')),
                ('interest_expense', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Interest incurred during the reporting period on all liabilities, including any client deposit accounts held by the organization, borrowings, subordinated debt, and other liabilities.', null=True, verbose_name=b'Interest Expense')),
                ('depreciation_and_amortization_expense', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of expenses recorded by the organization during the reporting period for depreciation and amortization.', null=True, verbose_name=b'Depreciation and Amortization Expense')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of corporate income taxes expensed by the organization during the reporting period.', null=True, verbose_name=b'Taxes')),
                ('net_income_before_donations', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Net Income or change in unrestricted net assets resulting from all business activities during the reporting period, excluding donations. The organization's net profit before donations.", null=True, verbose_name=b'Net Income Before Donations')),
                ('contributed_revenue', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Contributed revenue during the reporting period. Includes both unrestricted and restricted operating grants and donations and in-kind contributions. Does NOT include equity grants for capital, grants that are intended for future operating periods, or gra', null=True, verbose_name=b'Contributed Revenue')),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Net Income or change in unrestricted net assets resulting from all business activities during the reporting period and all Contributed Revenue. The organization's net profit.", null=True, verbose_name=b'Net Income')),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all assets that are reasonably expected to be converted into cash within one year in the normal course of business. Current assets can include cash, accounts receivable, inventory, marketable securities, prepa.', null=True, verbose_name=b'Current Assets')),
                ('total_value_of_loans_and_investments', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of financial portfolio products including loans and investments in investees.', null=True, verbose_name=b'Total Value of Loans and Investments')),
                ('financial_assets', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all assets that represent debt, equity, and cash assets such as: stocks, bonds, mutual funds, cash, and cash management accounts.  Values of assets should be based upon fair market value where efficient second.', null=True, verbose_name=b'Financial Assets')),
                ('fixed_assets', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all long-term tangible assets  that are not expected to be converted into cash in the current or upcoming fiscal year, e.g., buildings, real estate, production equipment, and furniture. Sometimes called PLANT.', null=True, verbose_name=b'Fixed Assets')),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all assets.', null=True, verbose_name=b'Total Assets')),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"The sum of the organization's profits, cumulative from inception to the end of the reporting period, not paid out as dividends, but retained by the company to be reinvested in its core business or to pay debt. Also referred to as retained capital, accumul.", null=True, verbose_name=b'Retained Earnings')),
                ('accounts_payable', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all outstanding debts that must be paid within a given period of time in order to avoid default.', null=True, verbose_name=b'Accounts Payable')),
                ('accounts_receivable', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of outstanding debts from clients who received goods or services on credit.', null=True, verbose_name=b'Accounts Receivable')),
                ('current_liabilities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value, at the end of the reporting period, of all liabilities that are expected to be settled with one year in the normal course of business. Current liabilities can include accounts payable, lines of credit, or other short term debts.', null=True, verbose_name=b'Current Liabilities')),
                ('financial_liabilities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Value, at the end of the reporting period, of an organization's financial liabilities. Financial liabilities include all borrowed funds, deposits held, or other contractual obligations to deliver cash.", null=True, verbose_name=b'Financial Liabilities')),
                ('loans_payable', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"The remaining balance, at the end of the reporting period, on all the organization's outstanding debt obligations carried on the balance sheet.", null=True, verbose_name=b'Loans Payable')),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Value of organization's liabilities at the end of the reporting period.", null=True, verbose_name=b'Total Liabilities')),
                ('equity_or_net_assets', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'The residual interest, at the end of the reporting period, in the assets of the organization after deducting all its liabilities.', null=True, verbose_name=b'Equity or Net Assets')),
                ('cash_and_cash_equivalents_period_start', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Value of the organization's cash equivalents at the beginning of the reporting period.", null=True, verbose_name=b'Cash and Cash Equivalents- Period Start')),
                ('cash_flow_from_operating_activities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of cash flows during the reporting period related to operating activities. Operating activities are the principal revenue-producing activities of the entity and other activities that are not investing or financing activities.', null=True, verbose_name=b'Cash Flow from Operating Activities')),
                ('cash_flow_from_investing_activities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of cash flows during the reporting period related to investing activities by the organization. Investing activities are the acquisition and disposal of long-term assets and other investments that are not considered to be cash equivalents.', null=True, verbose_name=b'Cash Flow from Investing Activities')),
                ('cash_flow_from_financing_activities', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of cash flows during the reporting period related to financing activities by the organization. Financing activities are activities that result in changes in the size and composition of the contributed equity and borrowings of the organization.', null=True, verbose_name=b'Cash Flow from Financing Activities')),
                ('new_investment_capital', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Value of cash flows from the organization's financing activities (both loans and investments) during the reporting period.", null=True, verbose_name=b'New Investment Capital')),
                ('net_cash_flow', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'The net cash flow of the organization during the reporting period. Net cash flow equals inflows less outflows of cash and cash equivalents.', null=True, verbose_name=b'Net Cash Flow')),
                ('cash_and_cash_equivalents_period_end', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of the organizations cash equivalents at the end of the reporting period.', null=True, verbose_name=b'Cash and Cash Equivalents- Period End')),
                ('revenue_growth', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Growth in value of the organization's revenue from one reporting period to another.Calculation: (Earned Revenue in reporting period 2 - Earned Revenue in reporting period 1) / Earned Revenue in reporting period 1", null=True, verbose_name=b'Revenue Growth')),
                ('income_growth', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Growth in value of the organization's Net income Before Donations from one reporting period to another.Calculation: (Net Income Before Donations in reporting period 2 - Net Income Before Donations in reporting period 1) / Net Income Before Donations", null=True, verbose_name=b'Income Growth')),
                ('gross_margin', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Percent of earned revenues that the organization retains after incurring the direct costs associated with producing the goods and services sold by the company.Calculation: 'Cost of Goods Sold' / 'Earned Revenue'", null=True, verbose_name=b'Gross Margin')),
                ('operating_profit_margin', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Organization's effectiveness at managing costs and turning earned revenues into income.Calculation: (Net Income Before Donations + Taxes) / Earned Revenue", null=True, verbose_name=b'Operating Profit Margin')),
                ('working_capital', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b"Organization's operating liquidity.Calculation: Current Assets - Current Liabilities", null=True, verbose_name=b'Working Capital')),
                ('return_on_assets_roa', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Measurement of how well the organization uses assets to generate returns.Calculation: Net Income Before Donations / Average Total Assets Average Total Assets: (Total Assets at the beginning of the period + Total Assets at the end of the period) / 2', null=True, verbose_name=b'Return on Assets (ROA)')),
                ('return_on_equity_roe', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Measurement of commercial profitability.Calculation: Net Income Before Donations / Average Equity or Net Assets Average Equity or Net Assets: (Average Equity or Net Assets at the beginning of the period + Average Equity or Net Assets at the end of', null=True, verbose_name=b'Return on Equity (ROE)')),
                ('fixed_costs', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Costs that do not vary based on production or sales levels.', null=True, verbose_name=b'Fixed Costs')),
                ('entrepreneur_investment', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of the equity and/or other financial contribution in the organization provided by the entrepreneur/s at the time of investment.', null=True, verbose_name=b'Entrepreneur Investment')),
                ('community_service_donations', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Value of all charitable donations made by the organization', null=True, verbose_name=b'Community Service Donations')),
                ('board_of_directors', models.PositiveIntegerField(help_text=b"Number of members of organization's Board of Directors or other governing body, as of the end of the reporting period.", null=True, verbose_name=b'Board of Directors', blank=True)),
                ('female_ownership', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Percentage of the company that is female-owned as of the end of the reporting period.Calculation: number of total shares owned by females/number of total shares.Note: Where regional or local laws apply for calculating ownership by previously excluded', null=True, verbose_name=b'Female Ownership')),
                ('financial_statement_review', models.NullBooleanField(help_text=b"Indicate whether it is the organization's policy to produce financial statements that are verified annually by a certified accountant.", verbose_name=b'Financial Statement Review')),
                ('full_time_employees', models.PositiveIntegerField(help_text=b'Number of full-time employees at the end of the reporting period.', null=True, verbose_name=b'Full-time Employees', blank=True)),
                ('full_time_employees_female', models.PositiveIntegerField(help_text=b'Number of full-time female employees at the end of the reporting period.', null=True, verbose_name=b'Full-time Employees: Female', blank=True)),
                ('part_time_employees', models.PositiveIntegerField(help_text=b'Number of part-time employees at the end of the reporting period.', null=True, verbose_name=b'Part-time Employees', blank=True)),
                ('part_time_employees_female', models.PositiveIntegerField(help_text=b'Number of female part-time employees at the end of the reporting period.', null=True, verbose_name=b'Part-time Employees: Female', blank=True)),
                ('volunteer_hours_worked', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Total number of hours worked by volunteers that supported the organization during the reporting period.', null=True, verbose_name=b'Volunteer Hours Worked')),
                ('client_individuals', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Number of individuals or households who were clients during the reporting period.For microfinance clients, this refers to active clients.For healthcare providers, this refers to patients.Note: Organizations tracking households should report num', null=True, verbose_name=b'Client Individuals')),
                ('client_organizations', models.PositiveIntegerField(help_text=b'Number of businesses or other organizations that were clients during the reporting period.', null=True, verbose_name=b'Client Organizations', blank=True)),
                ('store_team_information', models.TextField(null=True, verbose_name=b'Key Officers (Name and title)', blank=True)),
                ('possible_form_of_financial_support', multiselectfield.db.fields.MultiSelectField(choices=[(b'1', b'Grant'), (b'2', b'Loan'), (b'3', b'Equity')], max_length=255, blank=True, help_text=b'Grant, Loan or investment', null=True, verbose_name=b'Possible form of financial support')),
                ('potential_size_of_investment', models.DecimalField(decimal_places=2, max_digits=19, blank=True, help_text=b'Potential size of investment in USD', null=True, verbose_name=b'Potential size of investment')),
                ('potential_use_of_investment', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=255, null=True, verbose_name=b'Potential use of investment', choices=[(b'1', b'Land/building'), (b'2', b'Equipment'), (b'3', b'Human resources development'), (b'4', b'Revolving Capital'), (b'Other', b'Other')])),
                ('possible_form_of_non_financial_support', multiselectfield.db.fields.MultiSelectField(choices=[(b'1', b'Strategy Planning'), (b'2', b'Financial Management'), (b'3', b'Operational Management'), (b'4', b'PR'), (b'5', b'HR'), (b'6', b'Legal'), (b'7', b'Market Access'), (b'8', b'External Relations'), (b'9', b'Techinical Expertise'), (b'10', b'Fundraising'), (b'Other', b'Others')], max_length=255, blank=True, help_text=b'Strategy, PR, Marketing, Legal, Operation Management, Financial Management', null=True, verbose_name=b'Possible form of non-financial support')),
                ('image', files_widget.fields.ImageField(max_length=200, null=True, blank=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(null=True, blank=True)),
                ('description', ckeditor.fields.RichTextField(null=True, blank=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ordering', models.PositiveIntegerField(null=True, blank=True)),
                ('facebook_url', models.URLField(max_length=255, null=True, blank=True)),
                ('twitter_url', models.URLField(max_length=255, null=True, blank=True)),
                ('linkedin_url', models.URLField(max_length=255, null=True, blank=True)),
                ('homepage_url', models.URLField(max_length=255, null=True, blank=True)),
                ('type_of_organization', models.CharField(default=b'social-enterprise', max_length=128, choices=[(b'social-enterprise', 'Social Enterprise'), (b'supporter', 'Supporters')])),
                ('status', models.IntegerField(default=-1, choices=[(1, 'Published'), (-1, 'Request for Approval'), (0, 'Draft')])),
                ('created_raw', models.DateTimeField(null=True, blank=True)),
                ('created', models.DateTimeField(null=True, blank=True)),
                ('changed', models.DateTimeField(null=True, blank=True)),
                ('published', models.DateTimeField(null=True, blank=True)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('jobs', models.ManyToManyField(related_name='organization_jobs', to='organization.Job')),
                ('productservice_type', models.ManyToManyField(related_name='productservice_type_topics', to='taxonomy.Topic', blank=True, help_text=b'Type of product or service provided by the organization', null=True, verbose_name=b'Product/Service Type')),
                ('published_by', models.ForeignKey(related_name='published_by', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('sector_activities', models.ManyToManyField(related_name='sector_activities_topics', to='taxonomy.Topic', blank=True, help_text=b"Primary sectors impacted by the organization's operations.", null=True, verbose_name=b'Sector Activities')),
                ('topics', models.ManyToManyField(related_name='topics', null=True, to='taxonomy.Topic', blank=True)),
                ('type_of_needs', models.ManyToManyField(related_name='type_of_needs', null=True, to='taxonomy.TypeOfNeed', blank=True)),
                ('type_of_supports', models.ManyToManyField(related_name='type_of_supports', null=True, to='taxonomy.TypeOfSupport', blank=True)),
            ],
            options={
                'ordering': ['-ordering'],
            },
            bases=('party.party', models.Model),
        ),
    ]
