# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0049_organizationassistance_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='has_participate_in_program',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_received_investment',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_taken_equity_in_fund_organization',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='has_taken_equity_in_startup',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_lead_investor',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_register_to_nia',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(default=b'startup', max_length=128, choices=[(b'startup', 'Startup'), (b'investor', 'Investors'), (b'supporter', 'Supporter')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='organizationassistance',
            name='is_required',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='does_provide_financial_supports',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='does_provide_service_and_facility',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='does_provide_working_spaces',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='has_invited_in_participants_team',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='has_specific_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='has_taken_equity_in_participating_team',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='is_acting_as_an_investor',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='is_own_working_space',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='program',
            name='is_partner',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_pre_seed_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_pre_series_a_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_seed_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_series_a_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_series_b_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='programbatch',
            name='has_series_c_stage',
            field=models.NullBooleanField(),
            preserve_default=True,
        ),
    ]
