# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_typeofoffice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='country',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='country',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='investortype',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organizationfunding',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organizationgrowthstage',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organizationproductlaunch',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='programtype',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofassistantship',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofattachment',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofbatch',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeoffinancialsource',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocusindustry',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeoffocussector',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeoffunding',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestment',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofinvestmentstage',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofoffice',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofstageofparticipant',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='typeofsupport',
            name='title_th',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='description_th',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='summary_th',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='title_th',
        ),
    ]
